use  cmr;
/*创建排序和注释字段*/
alter table bath add bath_sort integer;
alter table bath_sort add bs_sort integer;
alter table bath_sort add bs_annotion nvarchar(100);
alter table book add book_sort integer;
alter table book_article add article_sort integer;
alter table book_chapter add chapter_sort integer;
alter table diet add diet_sort integer;
alter table disease add disease_sort integer;
alter table disease_sort add dis_sort integer;
alter table disease_sort add dis_annotion nvarchar(100);
alter table doctor add doctor_sort integer;
alter table doctor_sort add ds_sort integer;
alter table doctor_sort add ds_annotion nvarchar(100);
alter table hospital add hospital_sort integer;
alter table md_sort add mds_sort integer;
alter table md_sort add mds_annotion nvarchar(100);
alter table medicine add medicine_sort integer;
alter table medicine_sort add ms_sort integer;
alter table medicine_sort add ms_annotion nvarchar(100);
alter table prescription add prescription_sort integer;
alter table prescription_sort add ps_sort integer;
alter table prescription_sort add ps_annotion nvarchar(100);
alter table tea add tea_sort integer;

/* timestramp创建：创建时间和最后操作时间的字段 */
alter table bath add column bath_start  timestamp  default current_timestamp comment '创建时间';
alter table bath add column bath_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table bath_sort add column bs_start  timestamp  default current_timestamp comment '创建时间';
alter table bath_sort add column bs_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table book add column book_start  timestamp  default current_timestamp comment '创建时间';
alter table book add column book_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table book_article add column article_start  timestamp  default current_timestamp comment '创建时间';
alter table book_article add column article_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table book_chapter add column chapter_start  timestamp  default current_timestamp comment '创建时间';
alter table book_chapter add column chapter_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table diet add column diet_start  timestamp  default current_timestamp comment '创建时间';
alter table diet add column diet_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table disease add column disease_start  timestamp  default current_timestamp comment '创建时间';
alter table disease add column disease_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table disease_hospital add column dh_start  timestamp  default current_timestamp comment '创建时间';
alter table disease_hospital add column dh_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table disease_sort add column dis_start  timestamp  default current_timestamp comment '创建时间';
alter table disease_sort add column dis_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table doctor add column doctor_start  timestamp  default current_timestamp comment '创建时间';
alter table doctor add column doctor_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table doctor_disease add column dd_start  timestamp  default current_timestamp comment '创建时间';
alter table doctor_disease add column dd_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table doctor_sort add column ds_start  timestamp  default current_timestamp comment '创建时间';
alter table doctor_sort add column ds_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table health add column health_start  timestamp  default current_timestamp comment '创建时间';
alter table health add column health_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table hospital add column hostipal_start  timestamp  default current_timestamp comment '创建时间';
alter table hospital add column hostipal_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table md_sort add column mds_start  timestamp  default current_timestamp comment '创建时间';
alter table md_sort add column mds_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table medicine add column medicine_start  timestamp  default current_timestamp comment '创建时间';
alter table medicine add column medicine_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table medicine_prescription add column mp_start  timestamp  default current_timestamp comment '创建时间';
alter table medicine_prescription add column mp_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table medicine_sort add column ms_start  timestamp  default current_timestamp comment '创建时间';
alter table medicine_sort add column ms_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table prescription add column prescription_start  timestamp  default current_timestamp comment '创建时间';
alter table prescription add column prescription_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table prescription_disease add column pd_start  timestamp  default current_timestamp comment '创建时间';
alter table prescription_disease add column pd_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table prescription_sort add column ps_start  timestamp  default current_timestamp comment '创建时间';
alter table prescription_sort add column ps_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;
alter table tea add column tea_start  timestamp  default current_timestamp comment '创建时间';
alter table tea add column tea_end timestamp  default current_timestamp on update current_timestamp  comment'最后操作时间' ;

